# Generated by Django 4.0.3 on 2022-06-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_text', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='SessionCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SessionText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_text', models.CharField(max_length=250)),
                ('s_type', models.CharField(max_length=1)),
                ('s_id', models.IntegerField()),
                ('s_key', models.CharField(max_length=32)),
            ],
        ),
    ]
