# Generated by Django 4.0.3 on 2022-05-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasa2app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_count', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='answer',
            name='a_date',
        ),
        migrations.RemoveField(
            model_name='question',
            name='q_date',
        ),
    ]
