# Generated by Django 4.0.3 on 2022-05-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasa2app', '0002_submitcount_remove_answer_a_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitcount',
            name='s_count',
            field=models.IntegerField(),
        ),
    ]
